### PR TITLE
PR: support cloudflare pages functions

### LINKED ISSUE #12: Support pages functions deployment
We have started to use [Cloudflare pages function](https://developers.cloudflare.com/pages/functions/) in https://github.com/ubiquity/pay.ubq.fi/pull/226 . **cloudflare-deploy-action** does not support the deployment of pages function. It only deploys static files.

For pages functions to work, it is necessary to have functions files in a `functions` directory. This directory must be the one where we run `wrangler pages deploy`. It appears when this action runs the `wrangler pages deploy`, the current directory is not where the `functions` directory is present.

For this to work, the cloudflare-deploy-action needs some changes but it also must support whatever is working already in static-only projects.

### PR DESCRIPTION
**Pull request by EresDev**
Resolves #12

## QA - static only project
The changes should be backward compatible. The existing static-only projects should keep working without requiring any change. I have used a fork of ubiquity/work.ubq.fi to test this.
workflow: https://github.com/EresDevOrg/work.ubq.fi-2/actions/runs/9423832718/job/25962973041
deployment: https://8f190d0e.work-ubq-fi-2.pages.dev/

## QA - project with pages functions
It should deploy Cloudflare pages static files, and Cloudflare pages functions.

workflow: https://github.com/EresDevOrg/gift-card-pay.ubq.fi-2/actions/runs/9423625045/job/25962649398
deployment:
```
https://26f58827.gift-card-pay-ubq-fi-2.pages.dev/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyNzAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjgyMzk0MzE1NDk3NDc3Njk1MTUwOTA4NTM5OTU5MDAwNDUwOTA0NjI0MTMzNzkwMTEyMjY4NjI0NTI5MzMzNTkwMjM5NTA5NjA5Mzg2IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHhmMzlGZDZlNTFhYWQ4OEY2RjRjZTZhQjg4MjcyNzljZmZGYjkyMjY2IiwicmVxdWVzdGVkQW1vdW50IjoiMjcwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDcwOTk3OTcwQzUxODEyZGMzQTAxMEM3ZDAxYjUwZTBkMTdkYzc5QzgiLCJzaWduYXR1cmUiOiIweDExMTY4NTZjZGNmMTA3Nzg1Yjk0Yzc5NzNlMGI4YzUzZTU1N2JiZTg3NzBmNjgzZDk2NWQ3NWI0ODYyYzYwYjg2NWIyYzVkYTA5YzBiY2RjZWE4MzI1ZDZmNjg0Njk3NGQzMzQ2OTEyYmZmMzMyZmI2ODJiNGQzMjA3MmM0ODY5MWMiLCJuZXR3b3JrSWQiOjEwMH0seyJ0eXBlIjoiZXJjMjAtcGVybWl0IiwicGVybWl0Ijp7InBlcm1pdHRlZCI6eyJ0b2tlbiI6IjB4ZTkxRDE1M0UwYjQxNTE4QTJDZThEZDNENzk0NEZhODYzNDYzYTk3ZCIsImFtb3VudCI6IjkwMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI4MTAzMzgwOTUzMzEzMjQzODc1NzM4MDg2NjA4MjYyMDY0MjczMTE0NTUwMzg0OTgwNzYxMzg2NDMzNjY3MTM0MjczMTEzODY2MzAwMyIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4ZjM5RmQ2ZTUxYWFkODhGNkY0Y2U2YUI4ODI3Mjc5Y2ZmRmI5MjI2NiIsInJlcXVlc3RlZEFtb3VudCI6IjkwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDcwOTk3OTcwQzUxODEyZGMzQTAxMEM3ZDAxYjUwZTBkMTdkYzc5QzgiLCJzaWduYXR1cmUiOiIweDExMTY4NTZjZGNmMTA3Nzg1Yjk0Yzc5NzNlMGI4YzUzZTU1N2JiZTg3NzBmNjgzZDk2NWQ3NWI0ODYyYzYwYjg2NWIyYzVkYTA5YzBiY2RjZWE4MzI1ZDZmNjg0Njk3NGQzMzQ2OTEyYmZmMzMyZmI2ODJiNGQzMjA3MmM0ODY5MWMiLCJuZXR3b3JrSWQiOjEwMH1d
```

### CODE REVIEW

**Comment by rndquu** [comment]
@EresDev 

So if we need to deploy both static files and cloudflare pages functions we need the following github artifact structure:
```
github_artifact_folder
    static_html_files
        index.html
    functions
```

If we need to deploy only static files we need the following github artifact structure:
```
github_artifact_folder
    index.html
```

Correct? If so could you add this info to the README file for future reference.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by EresDev** [comment]
> Correct? If so could you add this info to the README file for future reference.

You are right. 

However, a better approach came into my mind today and I have re-done this today. 

What was the issue with my previous submission? It worked, but it was not as clean as the new solution. `output_directory` parameter was being used for two different purposes. One, to extract artifact into. Second, to use it as static directory name. It was okay if the entire directory was static, but now it is confusing when we have backend functions and whole output_directory is not a static directory. The new solution introduces a new parameter `statics_directory` to decouple both. It also offers an opportunity to move all old and new projects to the same directory structure, while still supporting old directory structure. 

I have added the info to readme, and I have also updated the QA links. 
@rndquu

**Review by rndquu — APPROVED** [review]

**Review by 0x4007 — APPROVED** [review]
Code looks fine

**Comment by 0x4007** [comment]
@EresDev doesn't seem to work anymore. Should not have to rely on a pull request. Should deploy on every commit.

https://github.com/ubiquity/pay.ubq.fi/actions/runs/9562570163/job/26359224909

I can leave it for another day or two for testing in production but otherwise will need to revert. 

Please prioritize this as it affects all of our projects. Thanks.

**Comment by EresDev** [comment]
> @EresDev doesn't seem to work anymore. Should not have to rely on a pull request. Should deploy on every commit.

I didn't change the trigger. So whatever the trigger (commit or pull) was set before this PR, it should work. But let me take a look, maybe it is breaking somewhere.

**Comment by 0x4007** [comment]
If needed, please work on the development branch directly. It might help you debug faster. 

We can revert if you can't figure it out in the next day or two.

**Comment by EresDev** [comment]
> Please prioritize this as it affects all of our projects. Thanks.

Ok, it appears there is no issue. It is working fine.
https://github.com/ubiquity/pay.ubq.fi/actions/runs/9564115180/job/26364104059

We need to understand a tricky part to know why it failed in your case. 
`development` branch uses artifact name: static
`beta` branch uses artifact name: full-stack-app

In your link, the "deploy to cloudflare" workflow was on development branch. It needed an artifact created by "build" workflow on the same branch. But the previous run of "build" workflow was "beta" branch. 

If "build" workflow runs before "deploy to cloudflare" there is no issue. You probably ran "deploy to cloudflare" manually, and last "build" was done by the different branch with a different artifact name. 

So, until we have gift-cards in beta branch, to build and deploy manually, first run the `build` workflow, and then run the `deploy to cloudflare` workflow. 

I have also run the deploy workflow on `work.ubq.fi` just to be safe, and it also worked fine. https://github.com/ubiquity/work.ubq.fi/actions/runs/9477343124/job/26363140008

**Comment by EresDev** [comment]
> > Please prioritize this as it affects all of our projects. Thanks.
> 
> Ok, it appears there is no issue. It is working fine. https://github.com/ubiquity/pay.ubq.fi/actions/runs/9564115180/job/26364104059
> 
> We need to understand a tricky part to know why it failed in your case. `development` branch uses artifact name: static `beta` branch uses artifact name: full-stack-app
> 
> In your link, the "deploy to cloudflare" workflow was on development branch. It needed an artifact created by "build" workflow on the same branch. But the previous run of "build" workflow was "beta" branch.
> 
> If "build" workflow runs before "deploy to cloudflare" there is no issue. You probably ran "deploy to cloudflare" manually, and last "build" was done by the different branch with a different artifact name.
> 
> So, until we have gift-cards in beta branch, to build and deploy manually, first run the `build` workflow, and then run the `deploy to cloudflare` workflow.
> 
> I have also run the deploy workflow on `work.ubq.fi` just to be safe, and it also worked fine. https://github.com/ubiquity/work.ubq.fi/actions/runs/9477343124/job/26363140008

The above info is correct if we want to deploy to development branch. The deploy of non-default branch still doesn't work. I am looking into it. 
All other projects should deploy correctly despite this. Only the gift-cards PR has issues.

**Comment by EresDev** [comment]
Deployment of branch `beta` `pay.ubq.fi` successfull: https://github.com/ubiquity/pay.ubq.fi/actions/runs/9568299929/job/26378171356

Deployment of branch `development` `pay.ubq.fi` successfull: https://github.com/ubiquity/pay.ubq.fi/actions/runs/9567051444/job/26377832050

Deployment of `work.ubq.fi` successfull: https://github.com/ubiquity/work.ubq.fi/actions/runs/9568407358


It is all working fine now. @0x4007

**Comment by 0x4007** [comment]
beta.pay.ubq.fi and pay.ubq.fi resolve to the same commit @rndquu 

http://alpha.beta.pay.ubq.fi/ (a made up one now for testing improperly config'd dynamic settings) does not resolve.

**Comment by rndquu** [comment]
> beta.pay.ubq.fi and pay.ubq.fi resolve to the same commit @rndquu
> 
> http://alpha.beta.pay.ubq.fi/ (a made up one now for testing improperly config'd dynamic settings) does not resolve.

https://github.com/ubiquity/pay.ubq.fi/pull/226#issuecomment-2177118616

**Pull request merged**
